title: Portfólio de Projetos 
description: "Projetos de Análise e Ciência de Dados\nFerramentas utilizadas: Python, SQL, Excel, Power BI\nAutor: Paulo Emílio Nery Assis Oliveira"
remote_theme: pages-themes/slate@v0.2.0
